app = "fly-autoscaler-scaler"

[build]
image = "flyio/fly-autoscaler:0.1"

[env]
FAS_APP_NAME = "fly-autoscaler-worker"
FAS_EXPR = "queue_depth / 10"
FAS_PROMETHEUS_ADDRESS = "https://api.fly.io/prometheus/fly-autoscaler-example"
FAS_PROMETHEUS_METRIC_NAME = "queue_depth"
FAS_PROMETHEUS_QUERY = "sum(queue_depth{app='fly-autoscaler-metric'})"

[metrics]
port = 9090
path = "/metrics"
